import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b">
          <nav className="max-w-6xl mx-auto px-4 py-3 flex gap-4">
            <a href="/listings" className="hover:underline">Listings</a>
            <a href="/submit" className="hover:underline">Submit</a>
            <a href="/admin" className="hover:underline">Admin</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
